/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\GitHub\\vuepress-theme-vdoing\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-34b0c870",
    path: "/ui/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34b0c870").then(next)
    },
  },
  {
    path: "/ui/index.html",
    redirect: "/ui/"
  },
  {
    path: "/00.目录页/02.页面.html",
    redirect: "/ui/"
  },
  {
    name: "v-61bfb1c1",
    path: "/web/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61bfb1c1").then(next)
    },
  },
  {
    path: "/web/index.html",
    redirect: "/web/"
  },
  {
    path: "/00.目录页/01.前端.html",
    redirect: "/web/"
  },
  {
    name: "v-b29c481a",
    path: "/more/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b29c481a").then(next)
    },
  },
  {
    path: "/more/index.html",
    redirect: "/more/"
  },
  {
    path: "/00.目录页/04.更多.html",
    redirect: "/more/"
  },
  {
    name: "v-6eadcaf2",
    path: "/technology/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6eadcaf2").then(next)
    },
  },
  {
    path: "/technology/index.html",
    redirect: "/technology/"
  },
  {
    path: "/00.目录页/03.技术.html",
    redirect: "/technology/"
  },
  {
    name: "v-68bd01e0",
    path: "/architecture/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68bd01e0").then(next)
    },
  },
  {
    path: "/architecture/index.html",
    redirect: "/architecture/"
  },
  {
    path: "/00.目录页/05.架构.html",
    redirect: "/architecture/"
  },
  {
    name: "v-248e926e",
    path: "/pages/beb6c0bd8a66cea6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-248e926e").then(next)
    },
  },
  {
    path: "/pages/beb6c0bd8a66cea6/index.html",
    redirect: "/pages/beb6c0bd8a66cea6/"
  },
  {
    path: "/06.收藏夹/01.网站.html",
    redirect: "/pages/beb6c0bd8a66cea6/"
  },
  {
    name: "v-67b02b80",
    path: "/pages/47cf96/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67b02b80").then(next)
    },
  },
  {
    path: "/pages/47cf96/index.html",
    redirect: "/pages/47cf96/"
  },
  {
    path: "/06.收藏夹/02.常用的前端轮子.html",
    redirect: "/pages/47cf96/"
  },
  {
    name: "v-5e7059c2",
    path: "/architecture/softwareArch/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e7059c2").then(next)
    },
  },
  {
    path: "/architecture/softwareArch/index.html",
    redirect: "/architecture/softwareArch/"
  },
  {
    path: "/11.架构/01.软件架构与需求分析/00.软件架构与需求分析目录.html",
    redirect: "/architecture/softwareArch/"
  },
  {
    name: "v-4ba85236",
    path: "/pages/9a7ee40fc232253e/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ba85236").then(next)
    },
  },
  {
    path: "/pages/9a7ee40fc232253e/index.html",
    redirect: "/pages/9a7ee40fc232253e/"
  },
  {
    path: "/03.技术/01.技术文档/01.Git使用手册.html",
    redirect: "/pages/9a7ee40fc232253e/"
  },
  {
    name: "v-22dd3514",
    path: "/pages/829589/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-22dd3514").then(next)
    },
  },
  {
    path: "/pages/829589/index.html",
    redirect: "/pages/829589/"
  },
  {
    path: "/_posts/随笔/我做了一个手写春联小网页，祝大家虎年暴富.html",
    redirect: "/pages/829589/"
  },
  {
    name: "v-0fabea38",
    path: "/pages/cd8bde/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0fabea38").then(next)
    },
  },
  {
    path: "/pages/cd8bde/index.html",
    redirect: "/pages/cd8bde/"
  },
  {
    path: "/_posts/随笔/拥抱生活，拥抱快乐.html",
    redirect: "/pages/cd8bde/"
  },
  {
    name: "v-6a4b6be4",
    path: "/pages/f2e63f/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a4b6be4").then(next)
    },
  },
  {
    path: "/pages/f2e63f/index.html",
    redirect: "/pages/f2e63f/"
  },
  {
    path: "/_posts/随笔/你知道的越多，不知道的也就越多.html",
    redirect: "/pages/f2e63f/"
  },
  {
    name: "v-920f84ea",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-920f84ea").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-2d221979",
    path: "/pages/a21cfc/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d221979").then(next)
    },
  },
  {
    path: "/pages/a21cfc/index.html",
    redirect: "/pages/a21cfc/"
  },
  {
    path: "/内容/01.架构/01.软件架构与需求分析(一).html",
    redirect: "/pages/a21cfc/"
  },
  {
    name: "v-4697c21e",
    path: "/pages/5fb08a/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4697c21e").then(next)
    },
  },
  {
    path: "/pages/5fb08a/index.html",
    redirect: "/pages/5fb08a/"
  },
  {
    path: "/内容/01.架构/02.软件架构与需求分析(二).html",
    redirect: "/pages/5fb08a/"
  },
  {
    name: "v-746dee8f",
    path: "/pages/dbf5e2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-746dee8f").then(next)
    },
  },
  {
    path: "/pages/dbf5e2/index.html",
    redirect: "/pages/dbf5e2/"
  },
  {
    path: "/内容/01.架构/03.软件架构与需求分析(三).html",
    redirect: "/pages/dbf5e2/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]