/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "JBlog",
  "description": "",
  "base": "/JBlog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/JBlog/img/favicon2.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "J"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#11a8cd"
      }
    ]
  ],
  "pages": [
    {
      "title": "前端",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "path": "01.前端",
            "imgUrl": "/img/web.png",
            "description": "JavaScript、ES6、Vue框架等前端技术"
          }
        },
        "title": "前端",
        "date": "2020-03-11T21:50:53.000Z",
        "permalink": "/web/",
        "sidebar": false,
        "article": false,
        "comment": false,
        "editLink": false,
        "author": {
          "name": "xugaoyi",
          "link": "https://github.com/xugaoyi"
        }
      },
      "regularPath": "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/01.%E5%89%8D%E7%AB%AF.html",
      "relativePath": "00.目录页/01.前端.md",
      "key": "v-61bfb1c1",
      "path": "/web/",
      "lastUpdated": "2022/06/09, 23:16:02",
      "lastUpdatedTimestamp": 1654787762000
    },
    {
      "title": "页面",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "path": "02.页面",
            "imgUrl": "/img/ui.png",
            "description": "html(5)/css(3)，前端页面相关技术"
          }
        },
        "title": "页面",
        "date": "2020-03-11T21:50:54.000Z",
        "permalink": "/ui/",
        "sidebar": false,
        "article": false,
        "comment": false,
        "editLink": false,
        "author": {
          "name": "xugaoyi",
          "link": "https://github.com/xugaoyi"
        }
      },
      "regularPath": "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/02.%E9%A1%B5%E9%9D%A2.html",
      "relativePath": "00.目录页/02.页面.md",
      "key": "v-34b0c870",
      "path": "/ui/",
      "lastUpdated": "2022/06/09, 23:16:02",
      "lastUpdatedTimestamp": 1654787762000
    },
    {
      "title": "更多",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "path": "04.更多",
            "imgUrl": "/img/more.png",
            "description": "学习、面试、在线工具等更多文章和页面"
          }
        },
        "title": "更多",
        "date": "2020-03-11T21:50:56.000Z",
        "permalink": "/more/",
        "sidebar": false,
        "article": false,
        "comment": false,
        "editLink": false,
        "author": {
          "name": "xugaoyi",
          "link": "https://github.com/xugaoyi"
        }
      },
      "regularPath": "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/04.%E6%9B%B4%E5%A4%9A.html",
      "relativePath": "00.目录页/04.更多.md",
      "key": "v-b29c481a",
      "path": "/more/",
      "lastUpdated": "2022/06/09, 23:16:02",
      "lastUpdatedTimestamp": 1654787762000
    },
    {
      "title": "技术",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "path": "03.技术",
            "imgUrl": "/img/other.png",
            "description": "技术文档、教程、技巧、总结等文章"
          }
        },
        "title": "技术",
        "date": "2020-03-11T21:50:55.000Z",
        "permalink": "/technology/",
        "sidebar": false,
        "article": false,
        "comment": false,
        "editLink": false,
        "author": {
          "name": "xugaoyi",
          "link": "https://github.com/xugaoyi"
        }
      },
      "regularPath": "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/03.%E6%8A%80%E6%9C%AF.html",
      "relativePath": "00.目录页/03.技术.md",
      "key": "v-6eadcaf2",
      "path": "/technology/",
      "lastUpdated": "2022/06/09, 23:16:02",
      "lastUpdatedTimestamp": 1654787762000
    },
    {
      "title": "Git使用手册",
      "frontmatter": {
        "title": "Git使用手册",
        "date": "2019-12-25T14:27:01.000Z",
        "permalink": "/pages/9a7ee40fc232253e",
        "categories": [
          "技术",
          "技术文档"
        ],
        "tags": [
          null
        ],
        "author": {
          "name": "xugaoyi",
          "link": "https://github.com/xugaoyi"
        }
      },
      "regularPath": "/03.%E6%8A%80%E6%9C%AF/01.%E6%8A%80%E6%9C%AF%E6%96%87%E6%A1%A3/01.Git%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C.html",
      "relativePath": "03.技术/01.技术文档/01.Git使用手册.md",
      "key": "v-4ba85236",
      "path": "/pages/9a7ee40fc232253e/",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "创建版本库（仓库）",
          "slug": "创建版本库-仓库"
        },
        {
          "level": 2,
          "title": "添加文件到仓库",
          "slug": "添加文件到仓库"
        },
        {
          "level": 2,
          "title": "版本管理",
          "slug": "版本管理"
        },
        {
          "level": 2,
          "title": "远程仓库",
          "slug": "远程仓库"
        },
        {
          "level": 2,
          "title": "分支管理",
          "slug": "分支管理"
        },
        {
          "level": 2,
          "title": "帮助命令",
          "slug": "帮助命令"
        },
        {
          "level": 2,
          "title": "参考文档",
          "slug": "参考文档"
        }
      ],
      "excerpt": "<h1 id=\"git使用手册\"><a class=\"header-anchor\" href=\"#git使用手册\">#</a> Git使用手册</h1>\n<h2 id=\"安装\"><a class=\"header-anchor\" href=\"#安装\">#</a> 安装</h2>\n<p>官网下载：<a href=\"https://git-scm.com/downloads\" target=\"_blank\" rel=\"noopener noreferrer\">https://git-scm.com/downloads<OutboundLink/></a> 下载完成后使用默认进行安装。</p>\n<p>安装完成后，在开始菜单里找到 <code>Git</code> -&gt; <code>Git Bash</code>，蹦出一个类似命令行窗口的东西，就说明Git安装成功！\n还需要最后一步设置，在命令行输入：</p>\n<!--beforebegin--><div class=\"language-bash extra-class\"><!--afterbegin--><pre v-pre class=\"language-bash\"><code><span class=\"token function\">git</span> config <span class=\"token parameter variable\">--global</span> user.name <span class=\"token string\">\"Your Name\"</span>\n<span class=\"token function\">git</span> config <span class=\"token parameter variable\">--global</span> user.email <span class=\"token string\">\"email@example.com\"</span>\n</code></pre>\n<!--beforeend--></div><!--afterend--><p>因为Git是分布式版本控制系统，所以，每个机器都必须自报家门：你的名字和Email地址。</p>\n",
      "lastUpdated": "2020/08/01, 14:31:12",
      "lastUpdatedTimestamp": 1596263472000
    },
    {
      "title": "网站",
      "frontmatter": {
        "title": "网站",
        "permalink": "/pages/beb6c0bd8a66cea6/",
        "date": "2020-04-19T11:33:04.000Z",
        "article": false,
        "author": {
          "name": "xugaoyi",
          "link": "https://github.com/xugaoyi"
        }
      },
      "regularPath": "/06.%E6%94%B6%E8%97%8F%E5%A4%B9/01.%E7%BD%91%E7%AB%99.html",
      "relativePath": "06.收藏夹/01.网站.md",
      "key": "v-248e926e",
      "path": "/pages/beb6c0bd8a66cea6/",
      "headers": [
        {
          "level": 2,
          "title": "推荐",
          "slug": "推荐"
        },
        {
          "level": 2,
          "title": "文档",
          "slug": "文档"
        },
        {
          "level": 2,
          "title": "社区",
          "slug": "社区"
        },
        {
          "level": 3,
          "title": "社区互动",
          "slug": "社区互动"
        },
        {
          "level": 2,
          "title": "技巧",
          "slug": "技巧"
        },
        {
          "level": 2,
          "title": "博客",
          "slug": "博客"
        },
        {
          "level": 2,
          "title": "电子书",
          "slug": "电子书"
        },
        {
          "level": 2,
          "title": "优秀文章",
          "slug": "优秀文章"
        },
        {
          "level": 2,
          "title": "视频",
          "slug": "视频"
        },
        {
          "level": 2,
          "title": "Github",
          "slug": "github"
        },
        {
          "level": 2,
          "title": "评论系统",
          "slug": "评论系统"
        },
        {
          "level": 2,
          "title": "前端小工具",
          "slug": "前端小工具"
        },
        {
          "level": 2,
          "title": "代码编辑",
          "slug": "代码编辑"
        },
        {
          "level": 2,
          "title": "Emoji表情",
          "slug": "emoji表情"
        },
        {
          "level": 2,
          "title": "图片工具",
          "slug": "图片工具"
        },
        {
          "level": 2,
          "title": "SVG",
          "slug": "svg"
        },
        {
          "level": 2,
          "title": "音视频工具",
          "slug": "音视频工具"
        },
        {
          "level": 2,
          "title": "思维导图",
          "slug": "思维导图"
        },
        {
          "level": 2,
          "title": "CSS",
          "slug": "css"
        },
        {
          "level": 2,
          "title": "CDN加速",
          "slug": "cdn加速"
        },
        {
          "level": 2,
          "title": "网站托管",
          "slug": "网站托管"
        },
        {
          "level": 2,
          "title": "正则",
          "slug": "正则"
        },
        {
          "level": 2,
          "title": "其他",
          "slug": "其他"
        },
        {
          "level": 2,
          "title": "设计",
          "slug": "设计"
        },
        {
          "level": 2,
          "title": "图库",
          "slug": "图库"
        },
        {
          "level": 2,
          "title": "3D",
          "slug": "_3d"
        },
        {
          "level": 2,
          "title": "交互",
          "slug": "交互"
        },
        {
          "level": 2,
          "title": "有趣",
          "slug": "有趣"
        },
        {
          "level": 2,
          "title": "生成器",
          "slug": "生成器"
        },
        {
          "level": 2,
          "title": "元宇宙",
          "slug": "元宇宙"
        },
        {
          "level": 2,
          "title": "教程",
          "slug": "教程"
        },
        {
          "level": 2,
          "title": "产品",
          "slug": "产品"
        },
        {
          "level": 2,
          "title": "实用",
          "slug": "实用"
        },
        {
          "level": 2,
          "title": "Talk",
          "slug": "talk"
        },
        {
          "level": 2,
          "title": "算法",
          "slug": "算法"
        },
        {
          "level": 2,
          "title": "nginx",
          "slug": "nginx"
        },
        {
          "level": 2,
          "title": "生活",
          "slug": "生活"
        }
      ],
      "excerpt": "<h1 id=\"个人收藏夹\"><a class=\"header-anchor\" href=\"#个人收藏夹\">#</a> 个人收藏夹</h1>\n<h2 id=\"推荐\"><a class=\"header-anchor\" href=\"#推荐\">#</a> 推荐</h2>\n<ul>\n<li><a href=\"https://panjiachen.github.io/awesome-bookmarks/\" target=\"_blank\" rel=\"noopener noreferrer\">panjiachen<OutboundLink/></a> by 花裤衩</li>\n<li><a href=\"https://www.code-nav.cn/\" target=\"_blank\" rel=\"noopener noreferrer\">编程导航<OutboundLink/></a> by 程序员鱼皮</li>\n<li><a href=\"https://r2coding.com/\" target=\"_blank\" rel=\"noopener noreferrer\">编程自学之路<OutboundLink/></a> by 程序羊</li>\n<li><a href=\"https://gitee.com/jishupang/web_atlas\" target=\"_blank\" rel=\"noopener noreferrer\">前端知识图谱+B站资源整合<OutboundLink/></a> by 技术胖</li>\n<li><a href=\"https://shengxinjing.cn/\" target=\"_blank\" rel=\"noopener noreferrer\">大圣编程自学网<OutboundLink/></a> by 大圣</li>\n<li><a href=\"https://devtool.tech/\" target=\"_blank\" rel=\"noopener noreferrer\">开发者武器库<OutboundLink/></a></li>\n<li><a href=\"https://www.fly63.com/tool/home.html\" target=\"_blank\" rel=\"noopener noreferrer\">工具大全<OutboundLink/></a></li>\n</ul>\n<p align=\"center\">\n<img src=\"https://fastly.jsdelivr.net/gh/xugaoyi/image_store@master/blog/qrcode.zdqv9mlfc0g.jpg\" width=\"200\">\n</p>\n<div class=\"center-container\"><p>关注公众号[有趣研究社]，回复<code>前端资源</code>，获取 <a href=\"https://github.com/xugaoyi/blog-gitalk-comment/wiki/Front-end-Study\" target=\"_blank\" rel=\"noopener noreferrer\">前端学习资料<OutboundLink/></a></p>\n</div>",
      "lastUpdated": "2022/10/14, 09:19:57",
      "lastUpdatedTimestamp": 1665710397000
    },
    {
      "title": "架构",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "path": "11.架构",
            "imgUrl": "/img/web.png",
            "description": "架构之路"
          }
        },
        "title": "架构",
        "date": "2022-12-20T21:55:53.000Z",
        "permalink": "/architecture/",
        "sidebar": false,
        "article": false,
        "comment": false,
        "editLink": false
      },
      "regularPath": "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/05.%E6%9E%B6%E6%9E%84.html",
      "relativePath": "00.目录页/05.架构.md",
      "key": "v-68bd01e0",
      "path": "/architecture/",
      "lastUpdated": "2023/01/09, 12:40:03",
      "lastUpdatedTimestamp": 1673239203000
    },
    {
      "title": "常用的前端轮子",
      "frontmatter": {
        "title": "常用的前端轮子",
        "date": "2021-10-09T19:42:02.000Z",
        "permalink": "/pages/47cf96/",
        "article": false,
        "author": {
          "name": "xugaoyi",
          "link": "https://github.com/xugaoyi"
        }
      },
      "regularPath": "/06.%E6%94%B6%E8%97%8F%E5%A4%B9/02.%E5%B8%B8%E7%94%A8%E7%9A%84%E5%89%8D%E7%AB%AF%E8%BD%AE%E5%AD%90.html",
      "relativePath": "06.收藏夹/02.常用的前端轮子.md",
      "key": "v-67b02b80",
      "path": "/pages/47cf96/",
      "headers": [
        {
          "level": 2,
          "title": "React UI 组件库",
          "slug": "react-ui-组件库"
        },
        {
          "level": 2,
          "title": "Vue UI组件库",
          "slug": "vue-ui组件库"
        },
        {
          "level": 2,
          "title": "常用效果组件",
          "slug": "常用效果组件"
        },
        {
          "level": 2,
          "title": "工具类",
          "slug": "工具类"
        },
        {
          "level": 2,
          "title": "Vue工具类",
          "slug": "vue工具类"
        },
        {
          "level": 2,
          "title": "其他",
          "slug": "其他"
        }
      ],
      "lastUpdated": "2022/04/12, 14:38:08",
      "lastUpdatedTimestamp": 1649745488000
    },
    {
      "title": "你知道的越多，不知道的也就越多",
      "frontmatter": {
        "title": "你知道的越多，不知道的也就越多",
        "date": "2020-05-06T15:52:40.000Z",
        "permalink": "/pages/f2e63f",
        "sidebar": "auto",
        "categories": [
          "随笔"
        ],
        "tags": [
          "学习",
          "知识",
          "鸡汤"
        ],
        "author": {
          "name": "xugaoyi",
          "link": "https://github.com/xugaoyi"
        }
      },
      "regularPath": "/_posts/%E9%9A%8F%E7%AC%94/%E4%BD%A0%E7%9F%A5%E9%81%93%E7%9A%84%E8%B6%8A%E5%A4%9A%EF%BC%8C%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84%E4%B9%9F%E5%B0%B1%E8%B6%8A%E5%A4%9A.html",
      "relativePath": "_posts/随笔/你知道的越多，不知道的也就越多.md",
      "key": "v-6a4b6be4",
      "path": "/pages/f2e63f/",
      "excerpt": "<p>不知道大家有没有发现，我们身边经常有这样的人，他们越是有能力的，越是有知识的，越是低调，越是谦逊，因为他们深知，知道的越多，不知道的也就越多。</p>\n",
      "lastUpdated": "2021/05/03, 01:04:55",
      "lastUpdatedTimestamp": 1619975095000
    },
    {
      "title": "我做了一个手写春联小网页，祝大家虎年暴富",
      "frontmatter": {
        "title": "我做了一个手写春联小网页，祝大家虎年暴富",
        "date": "2022-01-28T14:59:51.000Z",
        "permalink": "/pages/829589/",
        "titleTag": "原创",
        "sidebar": "auto",
        "categories": [
          "随笔"
        ],
        "tags": [
          null
        ],
        "author": {
          "name": "xugaoyi",
          "link": "https://github.com/xugaoyi"
        }
      },
      "regularPath": "/_posts/%E9%9A%8F%E7%AC%94/%E6%88%91%E5%81%9A%E4%BA%86%E4%B8%80%E4%B8%AA%E6%89%8B%E5%86%99%E6%98%A5%E8%81%94%E5%B0%8F%E7%BD%91%E9%A1%B5%EF%BC%8C%E7%A5%9D%E5%A4%A7%E5%AE%B6%E8%99%8E%E5%B9%B4%E6%9A%B4%E5%AF%8C.html",
      "relativePath": "_posts/随笔/我做了一个手写春联小网页，祝大家虎年暴富.md",
      "key": "v-22dd3514",
      "path": "/pages/829589/",
      "headers": [
        {
          "level": 3,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 3,
          "title": "产品构思",
          "slug": "产品构思"
        },
        {
          "level": 3,
          "title": "设计",
          "slug": "设计"
        },
        {
          "level": 3,
          "title": "开发",
          "slug": "开发"
        }
      ],
      "excerpt": "<p>手写春联：<a href=\"https://cl.xugaoyi.com/\" target=\"_blank\" rel=\"noopener noreferrer\">https://cl.xugaoyi.com/<OutboundLink/></a></p>\n<h3 id=\"前言\"><a class=\"header-anchor\" href=\"#前言\">#</a> 前言</h3>\n<p>虎年春节快到了，首先祝大家新年快乐，轻松暴富。\n最近在网上经常看到生成春联的文章，不过这些小demo要么功能简陋,要么UI特别‘程序员’，满足不了我挑剔的眼光。干脆我自己做一个吧，顺便简单体验一下vite+vue3。（因为页面相对简单，vue组件风格还是使用选项式api，重点还是想把产品快速做出来。）</p>\n",
      "lastUpdated": "2022/04/12, 14:38:08",
      "lastUpdatedTimestamp": 1649745488000
    },
    {
      "title": "架构",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "path": "内容/01.架构",
            "description": "架构之路"
          }
        },
        "title": "架构",
        "date": "2022-12-20T21:55:53.000Z",
        "permalink": "/architecture/softwareArch/",
        "sidebar": false,
        "article": false,
        "comment": false,
        "editLink": false
      },
      "regularPath": "/11.%E6%9E%B6%E6%9E%84/01.%E8%BD%AF%E4%BB%B6%E6%9E%B6%E6%9E%84%E4%B8%8E%E9%9C%80%E6%B1%82%E5%88%86%E6%9E%90/00.%E8%BD%AF%E4%BB%B6%E6%9E%B6%E6%9E%84%E4%B8%8E%E9%9C%80%E6%B1%82%E5%88%86%E6%9E%90%E7%9B%AE%E5%BD%95.html",
      "relativePath": "11.架构/01.软件架构与需求分析/00.软件架构与需求分析目录.md",
      "key": "v-5e7059c2",
      "path": "/architecture/softwareArch/",
      "lastUpdated": "2023/01/09, 12:40:03",
      "lastUpdatedTimestamp": 1673239203000
    },
    {
      "title": "拥抱生活，拥抱快乐",
      "frontmatter": {
        "title": "拥抱生活，拥抱快乐",
        "date": "2020-06-26T20:40:38.000Z",
        "permalink": "/pages/cd8bde/",
        "sidebar": "auto",
        "categories": [
          "随笔"
        ],
        "tags": [
          "鸡汤"
        ],
        "author": {
          "name": "xugaoyi",
          "link": "https://github.com/xugaoyi"
        }
      },
      "regularPath": "/_posts/%E9%9A%8F%E7%AC%94/%E6%8B%A5%E6%8A%B1%E7%94%9F%E6%B4%BB%EF%BC%8C%E6%8B%A5%E6%8A%B1%E5%BF%AB%E4%B9%90.html",
      "relativePath": "_posts/随笔/拥抱生活，拥抱快乐.md",
      "key": "v-0fabea38",
      "path": "/pages/cd8bde/",
      "excerpt": "<p>生活在后现代的今天，很多人都有一种虚无感，认为人生没有意义。但是，人生不可能没有意义，因为当你认为没有意义的时候，一定有一个与之相对应的概念叫有意义。</p>\n",
      "lastUpdated": "2020/08/01, 14:31:12",
      "lastUpdatedTimestamp": 1596263472000
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "tagline": "二两桃花酿作酒，万杯不及你温柔"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-920f84ea",
      "path": "/",
      "lastUpdated": "2023/01/09, 12:40:03",
      "lastUpdatedTimestamp": 1673239203000
    },
    {
      "title": "软件架构与需求分析(一)",
      "frontmatter": {
        "title": "软件架构与需求分析(一)",
        "date": "2022-12-20T22:00:51.000Z",
        "permalink": "/pages/a21cfc/"
      },
      "regularPath": "/%E5%86%85%E5%AE%B9/01.%E6%9E%B6%E6%9E%84/01.%E8%BD%AF%E4%BB%B6%E6%9E%B6%E6%9E%84%E4%B8%8E%E9%9C%80%E6%B1%82%E5%88%86%E6%9E%90(%E4%B8%80).html",
      "relativePath": "内容/01.架构/01.软件架构与需求分析(一).md",
      "key": "v-2d221979",
      "path": "/pages/a21cfc/",
      "headers": [
        {
          "level": 2,
          "title": "1、软件架构体系",
          "slug": "_1、软件架构体系"
        },
        {
          "level": 3,
          "title": "1.1. 系统与子系统",
          "slug": "_1-1-系统与子系统"
        },
        {
          "level": 3,
          "title": "1.2. 模块、组件、服务",
          "slug": "_1-2-模块、组件、服务"
        },
        {
          "level": 3,
          "title": "1.3. 软件架构体系",
          "slug": "_1-3-软件架构体系"
        },
        {
          "level": 2,
          "title": "2. 架构原则",
          "slug": "_2-架构原则"
        },
        {
          "level": 3,
          "title": "2.1. 解耦",
          "slug": "_2-1-解耦"
        },
        {
          "level": 3,
          "title": "2.2. 分层",
          "slug": "_2-2-分层"
        },
        {
          "level": 3,
          "title": "2.3. 封装",
          "slug": "_2-3-封装"
        },
        {
          "level": 2,
          "title": "3. 架构的方法",
          "slug": "_3-架构的方法"
        },
        {
          "level": 3,
          "title": "3.1 业务架构",
          "slug": "_3-1-业务架构"
        },
        {
          "level": 3,
          "title": "3.2 功能架构",
          "slug": "_3-2-功能架构"
        },
        {
          "level": 3,
          "title": "3.3 系统架构",
          "slug": "_3-3-系统架构"
        },
        {
          "level": 3,
          "title": "3.4 技术架构",
          "slug": "_3-4-技术架构"
        },
        {
          "level": 3,
          "title": "3.5 数据架构",
          "slug": "_3-5-数据架构"
        },
        {
          "level": 3,
          "title": "3.6 部署架构",
          "slug": "_3-6-部署架构"
        }
      ],
      "lastUpdated": "2023/01/09, 12:40:03",
      "lastUpdatedTimestamp": 1673239203000
    },
    {
      "title": "软件架构与需求分析(二)",
      "frontmatter": {
        "title": "软件架构与需求分析(二)",
        "date": "2022-12-20T22:01:16.000Z",
        "permalink": "/pages/5fb08a/"
      },
      "regularPath": "/%E5%86%85%E5%AE%B9/01.%E6%9E%B6%E6%9E%84/02.%E8%BD%AF%E4%BB%B6%E6%9E%B6%E6%9E%84%E4%B8%8E%E9%9C%80%E6%B1%82%E5%88%86%E6%9E%90(%E4%BA%8C).html",
      "relativePath": "内容/01.架构/02.软件架构与需求分析(二).md",
      "key": "v-4697c21e",
      "path": "/pages/5fb08a/",
      "headers": [
        {
          "level": 2,
          "title": "1. 架构演进之路",
          "slug": "_1-架构演进之路"
        },
        {
          "level": 3,
          "title": "1.1. 单体架构",
          "slug": "_1-1-单体架构"
        },
        {
          "level": 3,
          "title": "1.2. 分布式架构",
          "slug": "_1-2-分布式架构"
        },
        {
          "level": 3,
          "title": "1.3. 微服务架构",
          "slug": "_1-3-微服务架构"
        },
        {
          "level": 2,
          "title": "2. 服务化",
          "slug": "_2-服务化"
        },
        {
          "level": 3,
          "title": "2.1 为什么需要服务化",
          "slug": "_2-1-为什么需要服务化"
        },
        {
          "level": 3,
          "title": "2.2 服务化的好处",
          "slug": "_2-2-服务化的好处"
        },
        {
          "level": 3,
          "title": "2.3 服务化的问题",
          "slug": "_2-3-服务化的问题"
        }
      ],
      "lastUpdated": "2023/01/09, 12:40:03",
      "lastUpdatedTimestamp": 1673239203000
    },
    {
      "title": "软件架构与需求分析(三)",
      "frontmatter": {
        "title": "软件架构与需求分析(三)",
        "date": "2022-12-21T19:30:12.000Z",
        "permalink": "/pages/dbf5e2/"
      },
      "regularPath": "/%E5%86%85%E5%AE%B9/01.%E6%9E%B6%E6%9E%84/03.%E8%BD%AF%E4%BB%B6%E6%9E%B6%E6%9E%84%E4%B8%8E%E9%9C%80%E6%B1%82%E5%88%86%E6%9E%90(%E4%B8%89).html",
      "relativePath": "内容/01.架构/03.软件架构与需求分析(三).md",
      "key": "v-746dee8f",
      "path": "/pages/dbf5e2/",
      "headers": [
        {
          "level": 2,
          "title": "1、常见的需求问题",
          "slug": "_1、常见的需求问题"
        },
        {
          "level": 3,
          "title": "1.1. 需求不明确",
          "slug": "_1-1-需求不明确"
        },
        {
          "level": 3,
          "title": "1.2. 需求理解不一样",
          "slug": "_1-2-需求理解不一样"
        },
        {
          "level": 3,
          "title": "1.3. 需求自身经常变动",
          "slug": "_1-3-需求自身经常变动"
        },
        {
          "level": 2,
          "title": "2. 需求获取",
          "slug": "_2-需求获取"
        },
        {
          "level": 3,
          "title": "2.1 需求来源",
          "slug": "_2-1-需求来源"
        },
        {
          "level": 3,
          "title": "2.2 需求分类",
          "slug": "_2-2-需求分类"
        },
        {
          "level": 3,
          "title": "2.3 获取步骤",
          "slug": "_2-3-获取步骤"
        },
        {
          "level": 2,
          "title": "3. 需求要素",
          "slug": "_3-需求要素"
        },
        {
          "level": 3,
          "title": "3.1 角色、场景",
          "slug": "_3-1-角色、场景"
        },
        {
          "level": 3,
          "title": "3.2 业务流程",
          "slug": "_3-2-业务流程"
        },
        {
          "level": 3,
          "title": "3.3 数据实体",
          "slug": "_3-3-数据实体"
        },
        {
          "level": 3,
          "title": "3.4 功能性需求",
          "slug": "_3-4-功能性需求"
        },
        {
          "level": 3,
          "title": "3.5 非功能性需求",
          "slug": "_3-5-非功能性需求"
        },
        {
          "level": 2,
          "title": "4. 案例：电商订单系统",
          "slug": "_4-案例-电商订单系统"
        },
        {
          "level": 3,
          "title": "4.1 概述",
          "slug": "_4-1-概述"
        },
        {
          "level": 3,
          "title": "4.2 角色",
          "slug": "_4-2-角色"
        },
        {
          "level": 3,
          "title": "4.3 场景(用例)",
          "slug": "_4-3-场景-用例"
        },
        {
          "level": 3,
          "title": "4.4 功能",
          "slug": "_4-4-功能"
        },
        {
          "level": 3,
          "title": "4.5 实体",
          "slug": "_4-5-实体"
        },
        {
          "level": 3,
          "title": "4.6 流程",
          "slug": "_4-6-流程"
        }
      ],
      "lastUpdated": "2023/01/09, 12:40:03",
      "lastUpdatedTimestamp": 1673239203000
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "前端",
        "link": "/web/",
        "items": [
          {
            "text": "前端文章",
            "items": [
              {
                "text": "JavaScript",
                "link": "/pages/8143cc480faf9a11/"
              }
            ]
          },
          {
            "text": "学习笔记",
            "items": [
              {
                "text": "《JavaScript教程》",
                "link": "/note/javascript/"
              },
              {
                "text": "《JavaScript高级程序设计》",
                "link": "/note/js/"
              },
              {
                "text": "《ES6 教程》",
                "link": "/note/es6/"
              },
              {
                "text": "《Vue》",
                "link": "/note/vue/"
              },
              {
                "text": "《React》",
                "link": "/note/react/"
              },
              {
                "text": "《TypeScript 从零实现 axios》",
                "link": "/note/typescript-axios/"
              },
              {
                "text": "《Git》",
                "link": "/note/git/"
              },
              {
                "text": "TypeScript",
                "link": "/pages/51afd6/"
              },
              {
                "text": "JS设计模式总结",
                "link": "/pages/4643cd/"
              }
            ]
          }
        ]
      },
      {
        "text": "页面",
        "link": "/ui/",
        "items": [
          {
            "text": "HTML",
            "link": "/pages/8309a5b876fc95e3/"
          },
          {
            "text": "CSS",
            "link": "/pages/0a83b083bdf257cb/"
          }
        ]
      },
      {
        "text": "技术",
        "link": "/technology/",
        "items": [
          {
            "text": "技术文档",
            "link": "/pages/9a7ee40fc232253e/"
          },
          {
            "text": "GitHub技巧",
            "link": "/pages/4c778760be26d8b3/"
          },
          {
            "text": "Nodejs",
            "link": "/pages/117708e0af7f0bd9/"
          },
          {
            "text": "博客搭建",
            "link": "/pages/41f87d890d0a02af/"
          }
        ]
      },
      {
        "text": "更多",
        "link": "/more/",
        "items": [
          {
            "text": "学习",
            "link": "/pages/f2a556/"
          },
          {
            "text": "面试",
            "link": "/pages/aea6571b7a8bae86/"
          },
          {
            "text": "心情杂货",
            "link": "/pages/2d615df9a36a98ed/"
          },
          {
            "text": "实用技巧",
            "link": "/pages/baaa02/"
          },
          {
            "text": "友情链接",
            "link": "/friends/"
          }
        ]
      },
      {
        "text": "关于",
        "link": "/about/"
      },
      {
        "text": "收藏",
        "link": "/pages/beb6c0bd8a66cea6/"
      },
      {
        "text": "架构",
        "link": "/architecture/",
        "items": [
          {
            "text": "软件架构与需求分析",
            "link": "/architecture/softwareArch/"
          }
        ]
      }
    ],
    "markdown": {
      "extractHeaders": [
        "h2",
        "h3",
        "h4",
        "h5",
        "h6"
      ]
    },
    "logo": "/img/logo.jpg",
    "searchMaxSuggestions": 10,
    "lastUpdated": "上次更新",
    "docsDir": "docs",
    "editLinks": true,
    "editLinkText": "编辑",
    "category": false,
    "tag": false,
    "archive": false,
    "bodyBgImg": [
      "/img/mybg.jpg"
    ],
    "bodyBgImgOpacity": 0.8,
    "sidebar": {
      "/00.目录页/": [
        [
          "01.前端.md",
          "前端",
          "/web/"
        ],
        [
          "02.页面.md",
          "页面",
          "/ui/"
        ],
        [
          "03.技术.md",
          "技术",
          "/technology/"
        ],
        [
          "04.更多.md",
          "更多",
          "/more/"
        ],
        [
          "05.架构.md",
          "架构",
          "/architecture/"
        ]
      ],
      "catalogue": {
        "前端": "/web/",
        "页面": "/ui/",
        "技术": "/technology/",
        "更多": "/more/",
        "架构": "/architecture/",
        "软件架构与需求分析目录": "/architecture/softwareArch/"
      },
      "/01.前端/": [
        {
          "title": "JavaScript文章",
          "collapsable": true,
          "children": [
            {
              "title": "三级目录",
              "collapsable": true,
              "children": []
            }
          ]
        },
        {
          "title": "学习笔记",
          "collapsable": true,
          "children": []
        }
      ],
      "/02.页面/": [
        {
          "title": "HTML",
          "collapsable": true,
          "children": []
        },
        {
          "title": "CSS",
          "collapsable": true,
          "children": []
        }
      ],
      "/03.技术/": [
        {
          "title": "技术文档",
          "collapsable": true,
          "children": [
            [
              "01.技术文档/01.Git使用手册.md",
              "Git使用手册",
              "/pages/9a7ee40fc232253e"
            ]
          ]
        },
        {
          "title": "GitHub技巧",
          "collapsable": true,
          "children": []
        }
      ],
      "/06.收藏夹/": [
        [
          "01.网站.md",
          "网站",
          "/pages/beb6c0bd8a66cea6/"
        ],
        [
          "02.常用的前端轮子.md",
          "常用的前端轮子",
          "/pages/47cf96/"
        ]
      ],
      "/11.架构/": [
        {
          "title": "软件架构与需求分析",
          "collapsable": true,
          "children": [
            [
              "01.软件架构与需求分析/00.软件架构与需求分析目录.md",
              "架构",
              "/architecture/softwareArch/"
            ]
          ]
        }
      ],
      "/《Vue》笔记/": [
        {
          "title": "基础",
          "collapsable": true,
          "children": []
        },
        {
          "title": "组件",
          "collapsable": true,
          "children": []
        }
      ],
      "/内容/": [
        {
          "title": "架构",
          "collapsable": true,
          "children": [
            [
              "01.架构/01.软件架构与需求分析(一).md",
              "软件架构与需求分析(一)",
              "/pages/a21cfc/"
            ],
            [
              "01.架构/02.软件架构与需求分析(二).md",
              "软件架构与需求分析(二)",
              "/pages/5fb08a/"
            ],
            [
              "01.架构/03.软件架构与需求分析(三).md",
              "软件架构与需求分析(三)",
              "/pages/dbf5e2/"
            ]
          ]
        }
      ]
    },
    "author": {
      "name": "J"
    },
    "footer": {
      "createYear": 2022
    }
  }
}